import {
  ArrowDown,
  ArrowDownToLine,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRight,
  ArrowRightFromLine,
  ArrowUp,
  ArrowUpNarrowWide,
  BadgeCheck,
  Ban,
  Bell,
  CalendarClock,
  CalendarX,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleArrowLeft,
  CircleArrowRight,
  CircleCheck,
  CircleMinus,
  CirclePause,
  CircleX,
  ClipboardList,
  Clock,
  Compass,
  Copy,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FilePenLine,
  FilePlus,
  FileText,
  Focus,
  FolderOpen,
  Funnel,
  FunnelX,
  GripVertical,
  Hourglass,
  House,
  Inbox,
  KeyRound,
  Link,
  Lock,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  MessageSquareDot,
  Minimize2,
  Minus,
  Moon,
  Move,
  OctagonAlert,
  Package,
  PanelRight,
  Pencil,
  Play,
  Plus,
  Printer,
  ReceiptText,
  RefreshCcwDot,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Shuffle,
  SquareKanban,
  Store,
  Sun,
  SunMoon,
  Trash2,
  TriangleAlert,
  Truck,
  Undo2,
  Upload,
  User,
  UserPlus,
  Users,
  Warehouse,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react'

import {
  AdjustLayout,
  Board,
  CutPlan,
  CutPlanPlus,
  EdgeBand,
  Grain,
  Offcut,
  RotatePiece,
  SawBlade,
} from './craft'

/**
 * Every icon the app draws, named by what it MEANS, never by what it looks like. Changing a glyph is
 * one line here; two meanings that happen to share a glyph today (confirmed and active) keep their
 * own names, so they can part later without touching a screen.
 *
 * `icons.test.ts` keeps the menu, the bottom bar and the states from sharing a glyph: CoreUI's
 * layers icon used to be Familias in the menu, «En cola» on an order and the material button at
 * once.
 */
export const ICONS = {
  // --- Places: the menu and the bottom bar ---
  home: House,
  quotes: FileText,
  newQuote: Plus,
  optimizer: CutPlan,
  // «Cotizar» as the sidebar's button: the menu's own plan, with a «+».
  quoteAction: CutPlanPlus,
  orders: ClipboardList,
  clients: Users,
  workshop: SquareKanban,
  // The hubs (`HUBS`): one entry each for the screens they hold, whose tabs are words alone.
  catalog: Package,
  stats: ChartColumn,
  admin: Settings,
  // Screens inside a hub, drawn where they are linked from (Inicio's stock row, an order's menu).
  lowStock: Warehouse,
  branches: Store,
  more: Menu,

  // --- States: an order, a quote, an activity, a catalog row ---
  confirmed: CircleCheck,
  queued: Hourglass,
  inProgress: Play,
  finished: BadgeCheck,
  dispatched: Truck,
  cancelled: Ban,
  draft: FilePenLine,
  sent: Send,
  changesRequested: MessageSquareDot,
  rejected: CircleX,
  expired: CalendarX,
  expiring: CalendarClock,
  pending: Clock,
  done: Check,
  active: CircleCheck,
  inactive: CircleMinus,
  stopped: CirclePause,
  priority: Zap,
  late: Clock,
  ok: CircleCheck,
  branchArrived: CircleArrowRight,
  branchLeft: CircleArrowLeft,

  // --- The trade ---
  board: Board,
  edgeBand: EdgeBand,
  cut: SawBlade,
  offcut: Offcut,
  grain: Grain,

  // --- Actions ---
  add: Plus,
  createQuote: FilePlus,
  addClient: UserPlus,
  edit: Pencil,
  copy: Copy,
  delete: Trash2,
  save: Save,
  check: Check,
  open: FolderOpen,
  download: Download,
  upload: Upload,
  link: Link,
  external: ExternalLink,
  invoice: ReceiptText,
  print: Printer,
  start: Play,
  alternative: Shuffle,
  retry: RefreshCw,
  sync: RefreshCcwDot,
  renewToken: KeyRound,
  rotatePiece: RotatePiece,
  move: Move,
  moveTo: ArrowRightFromLine,
  dragHandle: GripVertical,
  adjustLayout: AdjustLayout,
  fillDown: ArrowDownToLine,
  moveUp: ArrowUp,
  moveDown: ArrowDown,
  sortAsc: ArrowUpNarrowWide,
  sortDesc: ArrowDownWideNarrow,
  filter: Funnel,
  clearFilters: FunnelX,
  search: Search,
  overflow: EllipsisVertical,
  // Diagonal arrows, so they never read as «Ajustar a la vista» beside them in the canvas.
  fullscreen: Maximize2,
  exitFullscreen: Minimize2,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  fit: Focus,
  undo: Undo2,
  inspector: PanelRight,
  expandAll: ChevronsUpDown,
  collapseAll: ChevronsDownUp,
  close: X,
  minus: Minus,
  showPassword: Eye,
  hidePassword: EyeOff,

  // --- Direction ---
  back: ArrowLeft,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,

  // --- Account and shell ---
  profile: User,
  lock: Lock,
  email: Mail,
  logout: LogOut,
  notifications: Bell,
  themeLight: Sun,
  themeDark: Moon,
  themeAuto: SunMoon,

  // --- Notices ---
  warning: TriangleAlert,
  error: OctagonAlert,
  empty: Inbox,
  notFound: Compass,
} as const

export type IconName = keyof typeof ICONS

export const isIconName = (value: string): value is IconName => value in ICONS
